import mock from "./mock";
import trigger from "./trigger";
import { resetMocks } from "./mocks";
import confirm from "./confirm";
import fail from "./fail";
import { increaseBlock } from "./block";
import { getCurrentBlock } from "./block";
import { resetCurrentBlock } from "./block";
import { anything } from "./anything";
import normalize from "./normalize";
import replace from "./replace";
import { setCurrentNetwork as connect } from "./network";
export { mock, trigger, resetMocks, confirm, fail, increaseBlock, getCurrentBlock, resetCurrentBlock, anything, normalize, replace, connect };
