import mock from "./mock.evm";
import trigger from "./trigger.evm";
import { resetMocks } from "./mocks";
import confirm from "./confirm.evm";
import fail from "./fail.evm";
import { increaseBlock } from "./block";
import { getCurrentBlock } from "./block";
import { resetCurrentBlock } from "./block";
import { anything } from "./anything";
import normalize from "./normalize";
import replace from "./replace.evm";
import { setCurrentNetwork as connect } from "./network";
export { mock, trigger, resetMocks, confirm, fail, increaseBlock, getCurrentBlock, resetCurrentBlock, anything, normalize, replace, connect };
